version: "3.8"

services:
  app:  ## service name
    container_name: haha
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Seoul
    ports:
      - "9999:8080"
      
#services.app.container_name=haha
#service.app.build.context=.
#반복되는 내용 생략 가능